name: CI
on: push

jobs:

  build:
    name: "Build module"
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build & Code analysis
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Run unit test
        run: yarn run test

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            src/**/*.js
            src/**/*.js.map
            src/**/*.d.ts

  test:

    name: Node.js
    runs-on: ubuntu-latest

    env:
      YARN_IGNORE_NODE: 1

    needs: build

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:

      - name: 'Checkout the repository'
        uses: actions/checkout@v4

      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: yarn run test
